# Generated by Django 5.1.1 on 2024-09-03 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition_id', models.CharField(max_length=100)),
                ('password_hash', models.CharField(max_length=255)),
                ('date1', models.DateField()),
                ('date2', models.DateField()),
                ('date3', models.DateField()),
                ('date4', models.DateField()),
                ('date5', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('starter', models.CharField(blank=True, max_length=255, null=True)),
                ('main_course', models.CharField(blank=True, max_length=255, null=True)),
                ('dessert', models.CharField(blank=True, max_length=255, null=True)),
                ('theme', models.CharField(blank=True, max_length=255, null=True)),
                ('competition_id', models.CharField(blank=True, max_length=255, null=True)),
                ('date4', models.DateField()),
                ('date', models.DateField()),
            ],
        ),
    ]
