# Generated by Django 5.1.1 on 2024-09-03 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='date5',
        ),
        migrations.RemoveField(
            model_name='competitor',
            name='date4',
        ),
    ]
