# Generated by Django 5.1.1 on 2024-09-03 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_competition_date5_remove_competitor_date4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='date1',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='competition',
            name='date2',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='competition',
            name='date3',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='competition',
            name='date4',
            field=models.DateField(blank=True, null=True),
        ),
    ]
